### ISSUE TITLE
CRUD comments

### ISSUE THREAD

**Issue by MilletMorgan** [Weisteck/bail2sneakers#5]

**Comment by Weisteck** [comment]
@MilletMorgan je peux fermer cette issue ?
On a déjà merge dans la branche develop

🐬

**Comment by MilletMorgan** [comment]
Oui vas y tu peux la fermer



[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality5&>
16/05/21,
13:09:00
